ERROR - 2022-11-13 01:01:42 --> Error connecting to the database: Unknown database 'ci4_sipm_polda'
CRITICAL - 2022-11-13 01:01:42 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'ci4_sipm_polda'
#0 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 C:\Users\ganda\Documents\GitHub\SIPM_polda\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#5 C:\Users\ganda\Documents\GitHub\SIPM_polda\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#6 C:\Users\ganda\Documents\GitHub\SIPM_polda\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#7 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptLogin()
#8 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ganda\Documents\GitHub\SIPM_polda\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\ganda\\...')
#12 {main}
CRITICAL - 2022-11-13 02:18:18 --> Trying to get property 'id' of non-object
#0 C:\Users\ganda\Documents\GitHub\SIPM_polda\vendor\myth\auth\src\Models\UserModel.php(77): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\Users\\ganda\\...', 77, Array)
#1 C:\Users\ganda\Documents\GitHub\SIPM_polda\vendor\myth\auth\src\Controllers\AuthController.php(176): Myth\Auth\Models\UserModel->withGroup('user')
#2 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#3 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#4 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\Users\ganda\Documents\GitHub\SIPM_polda\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\ganda\\...')
#7 {main}
ERROR - 2022-11-13 02:31:13 --> Error connecting to the database: Unknown database 'ci4_sipm_polda'
ERROR - 2022-11-13 10:11:41 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-11-13 10:11:41 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 C:\Users\ganda\Documents\GitHub\SIPM_polda\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#5 C:\Users\ganda\Documents\GitHub\SIPM_polda\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#6 C:\Users\ganda\Documents\GitHub\SIPM_polda\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#7 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptLogin()
#8 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ganda\Documents\GitHub\SIPM_polda\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\ganda\\...')
#12 {main}
ERROR - 2022-11-13 10:12:58 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-11-13 10:12:58 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 C:\Users\ganda\Documents\GitHub\SIPM_polda\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#5 C:\Users\ganda\Documents\GitHub\SIPM_polda\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#6 C:\Users\ganda\Documents\GitHub\SIPM_polda\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#7 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptLogin()
#8 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\ganda\Documents\GitHub\SIPM_polda\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\Users\ganda\Documents\GitHub\SIPM_polda\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\ganda\\...')
#12 {main}
